language: node_js

script:
  - npm run-script test_coverage_baseline
  - npm run-script test
  - npm run-script merge_test_coverage
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run-script saucelabs; fi

after_success: npm run-script coveralls

env:
  global: 
    - secure: "geiYCMi76xabux6e5jXvIsNEalfHHO4KVyPtzo232S+b7Hy6ZWYJ1EFQkoFXizj1ydlr8FHfhXBqC7iHYk/Rsv9aLj/HQOM32tHR+27Bi/gYoDMEd8tuJJWI+t082QcD5+KJofZ1Dnoxf0P4SRHLdzzpoz8U983zTbKVQ7VmxS2IdWl3eNhFwYJORN7gjbDDkmJaidh8j0w7TEsdr0e+lGz4DmVRXheLuTqNr7gwmHgMxk3bTu4kyUdCk5JYdFRWbrmvSNBvaMD2cd8kBSTI6tzRIMfvm0Mb818s/ODAEF9NSmG3fesl0kXQZ1A6peoPXeTAAvbVA6wAgamZjpBdh5EY7KRb2jd6qVA6OPEA5UYG+ucDvqj1/vmNS86tH3sIUR3K2Oc9K8Kk0ueC8tL9zTOcswNWj87i6YBXB3DeFThEuvAYztJ5rMFRTH8JAdoNcFfHzLVSo4J9qrVEJGMKt4nkjYMz2kmav5FYysWg997u0umUp0jscoO/Ve8MNioHnG+vyQMNVEwQqSAFjiFKJRO7cuVH/ZnKFLvWxCG+4RMoAoH1s5hFgRx45NEod/ut+GzaVJFaa4utGQP3h9poWa6ElyfzmXV6htKl8BIBVImJKHZm3bmD8sHIOmKWRAjyk2eza3UzuAhjQ2hkZ5sfxmNblCeR/Qe5gMZ7BT0IuLY="
    - secure: "JicnyS8f60bkZO5+Kr+xwTaLTIX7bBMQiwAAZdxOykt4T+BlkAjqgXj7vc3PKADRklsAkJWn/7+QMioDCqiEKLcRxL6+7JdPmt11XflGTQP8iHt+0LKmSKiLO0VMyxVDJ7+t3derLGyW/Xn0xN18bg4v4Xf4uD+6O+NDw4ec68T4ygTJxoJ1pOj5V725Wc7JyUWh7DEZYf8Suv9rXdQtXIAbQjjxUhjJQNY3vUresVfLl0s/wGPxVzoHVX4uHJVAES/99FSwRWYafuifd8XPwAhR+KiVCbzDEWyWVUN4Lpl9nF0cMuxLsuEYoUNbzoSK8Sv5uaIPpVS9DC9z1qg3zCiL631WTmzs3aYZCUj8tZvjcGXXXAJgOXpSTMOfRPc8g5P5xHXOVb+oOSC6Qd0zku+I/p5f9HmRZ2cCw3nNuCgFJqwflKKlNhvHQ9zL5Eon06573zgwk1fhpC4JL84tgAFowx2xx9P3UIZoei8uZ+5QY5O2RRjfCoH5/OvcYNZ7wmr4Xg1k5yrgYYYRDnvBxtLQ8QFWd8W70N6uAsfOJcWmlTK5baxQ/lti/Qk7SrQ5a0yngg3Nf8AbX3WQI0pPTJIjC9a+ZjywAV19o1pJtAv0ougfMF/mcQyXsEkJLhog/1vc2CxZ0Js4ZpKI1L0wH0x+lDlG3Q9zkK2dwqPAfEU="
